### ISSUE TITLE
Unable to schedule meeting

### ISSUE THREAD

**Issue by louayshaat** [aws-samples/amazon-chime-sdk-multi-meeting-management#1]
post deployment, unable to schedule meeting
Lambda error
"2021-09-27T02:29:57.161Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'utils'\nRequire stack:\n- /var/task/schedule.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'utils'",
        "Require stack:",
        "- /var/task/schedule.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}"

**Comment by schuettc** [comment]
Sorry, had a slight .gitignore issue.  Utils folder was not loading.  Can you pull again and retry?  

c865487624824fc592a9f275756070d79384b078

**Comment by louayshaat** [comment]
Works perfectly now, thanks
